### ISSUE TITLE
App crashing after deploying to Vercel

### ISSUE THREAD

**Issue by K-Sikora** [HamedBahram/next-i18n#1]
After I pushed my website to Vercel I noticed that it started crashing and throwing errors in the console, then I checked it with this repo and it's the same:

![image](https://github.com/HamedBahram/next-i18n/assets/105585380/bf0b3662-6d2a-49f6-b296-a93c5719bd99)

**Comment by HamedBahram** [comment]
> After I pushed my website to Vercel I noticed that it started crashing and throwing errors in the console, then I checked it with this repo and it's the same:
> 
> ![image](https://user-images.githubusercontent.com/105585380/263816157-bf0b3662-6d2a-49f6-b296-a93c5719bd99.png)

Clone and compare my code to yours and see what you're doing differently. 
This code has successfully been deployed to Vercel  => https://next-i18n-ten.vercel.app/en

**Comment by K-Sikora** [comment]
This is a screenshot of https://next-i18n-ten.vercel.app, edge function crashes when I open the website.

**Comment by HamedBahram** [comment]
This is working correctly on my end.
