### ISSUE TITLE
bug: The middleware file is preventing the loading of photos in the public folder.

### ISSUE THREAD

**Issue by samansayar** [HamedBahram/next-i18n#2]
When I put the middleware file in my project, the photos that were in the public folder were not loaded.

I think the code snippet for this is🤷🏼‍♂️:
```typescript
export const config = {
  // Matcher ignoring `/_next/` and `/api/`
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)']
}
```

**Comment by HamedBahram** [comment]
You can copy all your images into an `images` folder inside the `public` folder and then exclude the `images` folder from running the middleware inside the config matcher like ↓

```js
export const config = {
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico|images).*)']
}
```
